import { execSync } from 'node:child_process';
import {
  cpSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { readLibraryName } from '../utils/cargo-manifest.ts';
import { requireFile } from '../utils/files.ts';
import { message } from '../utils/output.ts';
import { run } from '../utils/process.ts';

export interface ExportIosOptions {
  tauriDir: string;
  manifest?: string;
  header?: string;
  outputDir?: string;
}

interface TauriConfig {
  build?: {
    beforeBuildCommand?: unknown;
    frontendDist?: unknown;
  };
}

const IOS_TARGETS = [
  'aarch64-apple-ios',
  'aarch64-apple-ios-sim',
  'x86_64-apple-ios',
];

const ASSET_BUNDLE_INFO = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleIdentifier</key><string>dev.tauri-native.assets</string>
  <key>CFBundleName</key><string>TauriNativeAssets</string>
  <key>CFBundlePackageType</key><string>BNDL</string>
  <key>CFBundleVersion</key><string>1</string>
</dict></plist>
`;

export const GENERATED_PODSPEC = `Pod::Spec.new do |s|
  s.name = "TauriNativeGenerated"
  s.version = "0.0.0"
  s.summary = "Application-specific artifacts generated by @tauri-native/cli"
  s.homepage = "https://github.com/gronxb/tauri-native"
  s.license = { :type => "MIT" }
  s.authors = "tauri-native contributors"
  s.source = { :git => "https://github.com/gronxb/tauri-native.git", :branch => "main" }
  s.platform = :ios, "13.0"
  s.static_framework = true
  s.vendored_frameworks = "TauriNativeCore.xcframework"
  s.resources = "TauriNativeAssets.bundle"
end
`;

export function writeGeneratedPodspec(outputDirectory: string): string {
  const podspec = path.join(outputDirectory, 'TauriNativeGenerated.podspec');
  writeFileSync(podspec, GENERATED_PODSPEC);
  return podspec;
}

export function exportIos(options: ExportIosOptions): void {
  const workingDirectory = process.cwd();
  const tauriDirectory = path.resolve(workingDirectory, options.tauriDir);
  const manifest = options.manifest
    ? path.resolve(workingDirectory, options.manifest)
    : path.join(tauriDirectory, 'crates/app-core/Cargo.toml');
  const manifestDirectory = path.dirname(manifest);
  const header = options.header
    ? path.resolve(workingDirectory, options.header)
    : path.join(manifestDirectory, 'include/tauri_native.h');
  const outputDirectory = path.resolve(
    workingDirectory,
    options.outputDir ?? path.join(tauriDirectory, 'gen/tauri-native/ios')
  );
  const configPath = path.join(tauriDirectory, 'tauri.conf.json');

  for (const requiredPath of [manifest, header, configPath]) {
    requireFile(requiredPath);
  }

  const config = JSON.parse(readFileSync(configPath, 'utf8')) as TauriConfig;
  const frontendDirectory = path.dirname(tauriDirectory);
  if (typeof config.build?.beforeBuildCommand === 'string') {
    message(`Building the Tauri microfrontend in ${frontendDirectory}`);
    execSync(config.build.beforeBuildCommand, {
      cwd: frontendDirectory,
      stdio: 'inherit',
    });
  }

  if (typeof config.build?.frontendDist !== 'string') {
    throw new Error(`${configPath} must define build.frontendDist`);
  }

  const frontendDist = path.resolve(
    tauriDirectory,
    config.build.frontendDist
  );
  requireFile(path.join(frontendDist, 'index.html'));

  const libraryName = readLibraryName(manifest);
  const targetDirectory = path.join(tauriDirectory, 'target/tauri-native');
  const cargoEnvironment = {
    ...process.env,
    CARGO_TARGET_DIR: targetDirectory,
  };

  run('rustup', ['target', 'add', ...IOS_TARGETS]);
  for (const target of IOS_TARGETS) {
    run(
      'cargo',
      ['build', '--manifest-path', manifest, '--target', target, '--release'],
      { env: cargoEnvironment }
    );
  }

  mkdirSync(outputDirectory, { recursive: true });
  const framework = path.join(outputDirectory, 'TauriNativeCore.xcframework');
  const assetBundle = path.join(outputDirectory, 'TauriNativeAssets.bundle');
  const universalDirectory = path.join(
    targetDirectory,
    'ios-simulator-universal/release'
  );
  const universalLibrary = path.join(
    universalDirectory,
    `lib${libraryName}.a`
  );

  mkdirSync(universalDirectory, { recursive: true });
  run('lipo', [
    '-create',
    path.join(
      targetDirectory,
      `aarch64-apple-ios-sim/release/lib${libraryName}.a`
    ),
    path.join(
      targetDirectory,
      `x86_64-apple-ios/release/lib${libraryName}.a`
    ),
    '-output',
    universalLibrary,
  ]);

  rmSync(framework, { recursive: true, force: true });
  run('xcodebuild', [
    '-create-xcframework',
    '-library',
    path.join(
      targetDirectory,
      `aarch64-apple-ios/release/lib${libraryName}.a`
    ),
    '-headers',
    path.dirname(header),
    '-library',
    universalLibrary,
    '-headers',
    path.dirname(header),
    '-output',
    framework,
  ]);

  rmSync(assetBundle, { recursive: true, force: true });
  cpSync(frontendDist, assetBundle, { recursive: true });
  writeFileSync(path.join(assetBundle, 'Info.plist'), ASSET_BUNDLE_INFO);
  const podspec = writeGeneratedPodspec(outputDirectory);

  message(
    `Created ${framework}\nCreated ${assetBundle}\nCreated ${podspec}`,
    '◆ '
  );
}
