source 'https://cdn.cocoapods.org/'

plugin 'cocoapods-lynx-library'

platform :ios, '13.0'
use_modular_headers!

output_dir = File.expand_path('tauri-native', __dir__)

target 'Hello-Lynx' do
  pod 'TauriNativeGenerated', :path => output_dir
  pod 'Lynx', '4.0.1', :subspecs => ['Framework']
  pod 'PrimJS', '4.0.0', :subspecs => ['quickjs', 'napi']
  pod 'XElement', '4.0.1'

  use_lynx_library!
end
