import type { ConfigPlugin } from 'expo/config-plugins';
import type { ArtifactError } from '../../../scripts/artifacts.ts';

type Options = { artifactsDir?: string; tauriDir?: string };
type Platform = 'ios' | 'android';

const {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} = require('node:fs') as typeof import('node:fs');
const { createRequire } = require('node:module') as typeof import('node:module');
const { tmpdir } = require('node:os') as typeof import('node:os');
const path = require('node:path') as typeof import('node:path');
import { readArtifacts } from '../../../scripts/artifacts.ts';

const packageName = '@tauri-native/react-native';
const generatedPodName = 'TauriNativeGenerated';
const generatedPodMarker = `  # Generated by ${packageName}`;
const androidAbis = [
  'arm64-v8a',
  'armeabi-v7a',
  'x86',
  'x86_64',
];
const androidCoreLibrary = 'libtauri_native_core.so';

function fail(message: string) {
  return new Error(`[${packageName}] ${message}`);
}

function projectRequire(projectRoot: string) {
  return createRequire(path.join(projectRoot, 'package.json'));
}

function resolveArtifacts(projectRoot: string, options: Options, platform: Platform) {
  if (options.artifactsDir && options.tauriDir) {
    throw fail('Choose "artifactsDir" or the legacy "tauriDir" convenience option, not both.');
  }
  const selected = options.artifactsDir ?? options.tauriDir;
  if (typeof selected !== 'string' || selected.trim() === '') {
    throw fail('Set "artifactsDir" to a host-owned directory containing the copied ios/ and android/ exports. Example: {"artifactsDir":"./tauri-native"}');
  }
  const root = path.resolve(projectRoot, selected);
  const directory = path.join(root, ...(options.artifactsDir ? [] : ['gen/tauri-native']), platform);
  try { readArtifacts(directory, platform); }
  catch (cause) { const error = cause as ArtifactError; throw Object.assign(fail(`${error.message} Supply a complete, matching CLI export before prebuild.`), { code: error.code }); }
  return directory;
}

function withArtifactCopy(source: string, platform: Platform, apply: (stage: string) => void) {
  const stage = mkdtempSync(path.join(tmpdir(), 'tauri-native-host-'));
  try {
    cpSync(source, stage, { recursive: true });
    // Validate the private copy too: an export/watch process can replace the
    // input directory between its initial check and this copy operation.
    readArtifacts(stage, platform);
    apply(stage);
  } finally { rmSync(stage, { recursive: true, force: true }); }
}

function generatedPodfile(platformProjectRoot: string) {
  const podfile = path.join(platformProjectRoot, 'Podfile');
  let source;

  try {
    source = readFileSync(podfile, 'utf8');
  } catch {
    throw fail(`Could not read the generated iOS Podfile at "${podfile}".`);
  }

  if (source.includes(generatedPodMarker)) {
    return { podfile, source };
  }

  const target = /^target\s+['"][^'"]+['"]\s+do\s*$/m;
  if (!target.test(source)) {
    throw fail(`Could not find an iOS target in "${podfile}".`);
  }

  const dependency = [
    generatedPodMarker,
    `  pod '${generatedPodName}', :path => './tauri-native'`,
  ].join('\n');
  return { podfile, source: source.replace(target, (line) => `${line}\n${dependency}`) };
}

function copyExportedArtifacts(projectRoot: string, platformProjectRoot: string, options: Options) {
  const exportDirectory = resolveArtifacts(projectRoot, options, 'ios');
  // Read/validate the Podfile before modifying any integration output.
  const pod = generatedPodfile(platformProjectRoot);
  const outputDir = path.join(platformProjectRoot, 'tauri-native');
  withArtifactCopy(exportDirectory, 'ios', stage => {
    rmSync(outputDir, { recursive: true, force: true });
    cpSync(stage, outputDir, { recursive: true });
    writeFileSync(pod.podfile, pod.source);
  });
}

function copyAndroidArtifacts(projectRoot: string, platformProjectRoot: string, options: Options) {
  const exportDirectory = resolveArtifacts(projectRoot, options, 'android');
  const appSource = path.join(platformProjectRoot, 'app/src/main');
  withArtifactCopy(exportDirectory, 'android', stage => {
    for (const abi of androidAbis) {
      const destinationDirectory = path.join(appSource, 'jniLibs', abi);
      mkdirSync(destinationDirectory, { recursive: true });
      cpSync(path.join(stage, 'jniLibs', abi, androidCoreLibrary), path.join(destinationDirectory, androidCoreLibrary));
    }
    const destinationAssets = path.join(appSource, 'assets/tauri-native');
    rmSync(destinationAssets, { recursive: true, force: true });
    cpSync(path.join(stage, 'assets/tauri-native'), destinationAssets, { recursive: true });
  });
}

const withTauriNative: ConfigPlugin<Options> = function withTauriNative(config, options = {}) {
  const configProjectRoot = config?._internal?.projectRoot ?? process.cwd();
  let withDangerousMod: typeof import('expo/config-plugins').withDangerousMod;

  try {
    ({ withDangerousMod } = projectRequire(configProjectRoot)(
      'expo/config-plugins'
    ));
  } catch {
    throw fail(
      `Could not load expo/config-plugins from "${configProjectRoot}". ` +
        'Install Expo SDK 57 in the consuming app.'
    );
  }

  const withIosArtifacts = withDangerousMod(config, [
    'ios',
    (modConfig) => {
      copyExportedArtifacts(
        modConfig.modRequest.projectRoot,
        modConfig.modRequest.platformProjectRoot,
        options
      );
      return modConfig;
    },
  ]);

  return withDangerousMod(withIosArtifacts, [
    'android',
    (modConfig) => {
      copyAndroidArtifacts(
        modConfig.modRequest.projectRoot,
        modConfig.modRequest.platformProjectRoot,
        options
      );
      return modConfig;
    },
  ]);
};

export = withTauriNative;
