'use strict';

const {
  cpSync,
  mkdirSync,
  statSync,
  readFileSync,
  rmSync,
  writeFileSync,
} = require('node:fs');
const { createRequire } = require('node:module');
const path = require('node:path');

const packageName = '@tauri-native/react-native';
const generatedPodName = 'TauriNativeGenerated';
const generatedPodMarker = `  # Generated by ${packageName}`;
const androidAbis = [
  'arm64-v8a',
  'armeabi-v7a',
  'x86',
  'x86_64',
];
const androidCoreLibrary = 'libtauri_native_core.so';

function fail(message) {
  return new Error(`[${packageName}] ${message}`);
}

function projectRequire(projectRoot) {
  return createRequire(path.join(projectRoot, 'package.json'));
}

function resolveTauriDir(projectRoot, tauriDir) {
  if (typeof tauriDir !== 'string' || tauriDir.trim() === '') {
    throw fail(
      'The Expo config plugin requires a non-empty "tauriDir" option. ' +
        'Example: ["@tauri-native/react-native", {"tauriDir":"../tauri/src-tauri"}]'
    );
  }

  const resolved = path.resolve(projectRoot, tauriDir);

  try {
    if (statSync(resolved).isDirectory()) {
      return resolved;
    }
  } catch {}

  throw fail(
    `tauriDir "${resolved}" is not a directory. ` +
      `The path is resolved relative to the Expo project root "${projectRoot}".`
  );
}

function addGeneratedPodToPodfile(platformProjectRoot) {
  const podfile = path.join(platformProjectRoot, 'Podfile');
  let source;

  try {
    source = readFileSync(podfile, 'utf8');
  } catch {
    throw fail(`Could not read the generated iOS Podfile at "${podfile}".`);
  }

  if (source.includes(generatedPodMarker)) {
    return;
  }

  const target = /^target\s+['"][^'"]+['"]\s+do\s*$/m;
  if (!target.test(source)) {
    throw fail(`Could not find an iOS target in "${podfile}".`);
  }

  const dependency = [
    generatedPodMarker,
    `  pod '${generatedPodName}', :path => './tauri-native'`,
  ].join('\n');
  writeFileSync(podfile, source.replace(target, (line) => `${line}\n${dependency}`));
}

function copyExportedArtifacts(projectRoot, platformProjectRoot, tauriDir) {
  const resolvedTauriDir = resolveTauriDir(projectRoot, tauriDir);
  const exportDirectory = path.join(
    resolvedTauriDir,
    'gen/tauri-native/ios'
  );
  const requiredArtifacts = [
    `${generatedPodName}.podspec`,
    'TauriNativeCore.xcframework',
    'TauriNativeAssets.bundle',
  ];

  for (const artifact of requiredArtifacts) {
    try {
      statSync(path.join(exportDirectory, artifact));
    } catch {
      throw fail(
        `Could not find exported iOS artifacts at "${exportDirectory}". ` +
          `Run "tauri-native export ios" from the Tauri project before Expo prebuild.`
      );
    }
  }

  const outputDir = path.join(platformProjectRoot, 'tauri-native');
  rmSync(outputDir, { recursive: true, force: true });
  cpSync(exportDirectory, outputDir, { recursive: true });
}

function copyAndroidArtifacts(projectRoot, platformProjectRoot, tauriDir) {
  const resolvedTauriDir = resolveTauriDir(projectRoot, tauriDir);
  const exportDirectory = path.join(
    resolvedTauriDir,
    'gen/tauri-native/android'
  );
  const exportedAssets = path.join(
    exportDirectory,
    'assets/tauri-native'
  );

  try {
    statSync(path.join(exportedAssets, 'index.html'));
    for (const abi of androidAbis) {
      statSync(
        path.join(exportDirectory, 'jniLibs', abi, androidCoreLibrary)
      );
    }
  } catch {
    throw fail(
      `Could not find exported Android artifacts at "${exportDirectory}". ` +
        `Run "tauri-native export android" from the Tauri project before Expo prebuild.`
    );
  }

  const appSource = path.join(platformProjectRoot, 'app/src/main');
  for (const abi of androidAbis) {
    const destinationDirectory = path.join(appSource, 'jniLibs', abi);
    mkdirSync(destinationDirectory, { recursive: true });
    cpSync(
      path.join(exportDirectory, 'jniLibs', abi, androidCoreLibrary),
      path.join(destinationDirectory, androidCoreLibrary)
    );
  }

  const destinationAssets = path.join(appSource, 'assets/tauri-native');
  rmSync(destinationAssets, { recursive: true, force: true });
  cpSync(exportedAssets, destinationAssets, { recursive: true });
}

module.exports = function withTauriNative(config, options = {}) {
  const configProjectRoot = config?._internal?.projectRoot ?? process.cwd();
  let withDangerousMod;

  try {
    ({ withDangerousMod } = projectRequire(configProjectRoot)(
      'expo/config-plugins'
    ));
  } catch {
    throw fail(
      `Could not load expo/config-plugins from "${configProjectRoot}". ` +
        'Install Expo SDK 57 in the consuming app.'
    );
  }

  const withIosArtifacts = withDangerousMod(config, [
    'ios',
    (modConfig) => {
      copyExportedArtifacts(
        modConfig.modRequest.projectRoot,
        modConfig.modRequest.platformProjectRoot,
        options?.tauriDir
      );
      addGeneratedPodToPodfile(modConfig.modRequest.platformProjectRoot);
      return modConfig;
    },
  ]);

  return withDangerousMod(withIosArtifacts, [
    'android',
    (modConfig) => {
      copyAndroidArtifacts(
        modConfig.modRequest.projectRoot,
        modConfig.modRequest.platformProjectRoot,
        options?.tauriDir
      );
      return modConfig;
    },
  ]);
};
